"""
Google Calendar Service - File-based OAuth with CRUD operations.
Auth via InstalledAppFlow token (generated by scripts/google_calendar_auth.py).
"""

import os
import json
from datetime import datetime, timedelta
from typing import List, Dict, Optional
from pathlib import Path

try:
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    from googleapiclient.discovery import build
    GOOGLE_API_AVAILABLE = True
except ImportError:
    GOOGLE_API_AVAILABLE = False
    print("Warning: Google API libraries not installed. Run: pip install google-auth-oauthlib google-api-python-client")

CLIENT_SECRET = '/data/projects/gmail-cleaner/credentials/client_secret.json'
TOKEN_PATH = Path(__file__).parent.parent.parent / 'credentials' / 'google_calendar_token.json'
SCOPES = ['https://www.googleapis.com/auth/calendar']
TIMEZONE = 'Europe/Paris'


class GoogleCalendarService:
    """Google Calendar API service with file-based auth and CRUD."""

    def __init__(self):
        self._service = None
        self._creds = None

    def is_available(self) -> bool:
        return GOOGLE_API_AVAILABLE

    def _load_credentials(self) -> Optional[Credentials]:
        if not GOOGLE_API_AVAILABLE:
            return None
        if not TOKEN_PATH.exists():
            return None

        creds = Credentials.from_authorized_user_file(str(TOKEN_PATH), SCOPES)

        if creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
                with open(TOKEN_PATH, 'w') as f:
                    f.write(creds.to_json())
            except Exception as e:
                print(f"Error refreshing Google Calendar token: {e}")
                return None

        if not creds.valid:
            return None

        return creds

    def _get_service(self):
        if self._service and self._creds and self._creds.valid:
            return self._service

        self._creds = self._load_credentials()
        if not self._creds:
            return None

        self._service = build('calendar', 'v3', credentials=self._creds)
        return self._service

    def is_authenticated(self) -> bool:
        return self._load_credentials() is not None

    def get_status(self) -> Dict:
        if not GOOGLE_API_AVAILABLE:
            return {'connected': False, 'reason': 'libraries_missing'}
        if not TOKEN_PATH.exists():
            return {'connected': False, 'reason': 'no_token'}

        creds = self._load_credentials()
        if not creds:
            return {'connected': False, 'reason': 'invalid_token'}

        return {'connected': True, 'email': 'fabrice.estezet@gmail.com'}

    # ---- READ ----

    def get_events(self, start_date: datetime, end_date: datetime) -> List[Dict]:
        service = self._get_service()
        if not service:
            return []

        try:
            time_min = start_date.isoformat() + '+01:00' if start_date.tzinfo is None else start_date.isoformat()
            time_max = end_date.isoformat() + '+01:00' if end_date.tzinfo is None else end_date.isoformat()

            events_result = service.events().list(
                calendarId='primary',
                timeMin=time_min,
                timeMax=time_max,
                singleEvents=True,
                orderBy='startTime',
                timeZone=TIMEZONE
            ).execute()

            return [self._simplify_event(e) for e in events_result.get('items', [])]

        except Exception as e:
            print(f"Error fetching events: {e}")
            return []

    def get_week_events(self, week_start: datetime) -> Dict[str, List[Dict]]:
        week_end = week_start + timedelta(days=7)
        events = self.get_events(week_start, week_end)

        days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche']
        by_day = {day: [] for day in days}

        for event in events:
            start = event.get('start', {})
            if 'dateTime' in start:
                event_date = datetime.fromisoformat(start['dateTime'])
            elif 'date' in start:
                event_date = datetime.strptime(start['date'], '%Y-%m-%d')
            else:
                continue

            day_index = event_date.weekday()
            if 0 <= day_index < 7:
                by_day[days[day_index]].append(event)

        return by_day

    # ---- CREATE ----

    def create_event(self, summary: str, start_datetime: str, end_datetime: str,
                     description: str = '', location: str = '',
                     all_day: bool = False) -> Optional[Dict]:
        service = self._get_service()
        if not service:
            return None

        if all_day:
            body = {
                'summary': summary,
                'start': {'date': start_datetime[:10]},
                'end': {'date': end_datetime[:10]},
            }
        else:
            body = {
                'summary': summary,
                'start': {'dateTime': start_datetime, 'timeZone': TIMEZONE},
                'end': {'dateTime': end_datetime, 'timeZone': TIMEZONE},
            }

        if description:
            body['description'] = description
        if location:
            body['location'] = location

        try:
            event = service.events().insert(calendarId='primary', body=body).execute()
            return self._simplify_event(event)
        except Exception as e:
            print(f"Error creating event: {e}")
            return None

    # ---- UPDATE ----

    def update_event(self, event_id: str, **kwargs) -> Optional[Dict]:
        service = self._get_service()
        if not service:
            return None

        try:
            event = service.events().get(calendarId='primary', eventId=event_id).execute()

            if 'summary' in kwargs:
                event['summary'] = kwargs['summary']
            if 'description' in kwargs:
                event['description'] = kwargs['description']
            if 'location' in kwargs:
                event['location'] = kwargs['location']
            if 'start_datetime' in kwargs:
                event['start'] = {'dateTime': kwargs['start_datetime'], 'timeZone': TIMEZONE}
            if 'end_datetime' in kwargs:
                event['end'] = {'dateTime': kwargs['end_datetime'], 'timeZone': TIMEZONE}

            updated = service.events().update(
                calendarId='primary', eventId=event_id, body=event
            ).execute()
            return self._simplify_event(updated)

        except Exception as e:
            print(f"Error updating event: {e}")
            return None

    # ---- DELETE ----

    def delete_event(self, event_id: str) -> bool:
        service = self._get_service()
        if not service:
            return False

        try:
            service.events().delete(calendarId='primary', eventId=event_id).execute()
            return True
        except Exception as e:
            print(f"Error deleting event: {e}")
            return False

    # ---- HELPERS ----

    def _simplify_event(self, event: Dict) -> Dict:
        return {
            'id': event.get('id'),
            'summary': event.get('summary', 'Sans titre'),
            'start': event.get('start'),
            'end': event.get('end'),
            'location': event.get('location', ''),
            'description': event.get('description', ''),
            'status': event.get('status'),
            'htmlLink': event.get('htmlLink'),
        }


google_calendar_service = GoogleCalendarService()
